project = u'domo-php'
copyright = u'2018, Wogan May'
author = u'Wogan May'
version = u''
release = u''
extensions = []
templates_path = ['_templates']
source_suffix = '.rst'
master_doc = 'index'
language = None
exclude_patterns = [u'_build', 'Thumbs.db', '.DS_Store']
pygments_style = 'sphinx'
html_theme = 'default'
html_static_path = ['_static']
htmlhelp_basename = 'domo-phpdoc'
latex_elements = {}
latex_documents = [(master_doc, 'domo-php.tex', u'domo-php Documentation', u'Wogan May', 'manual')]
man_pages = [(master_doc, 'domo-php', u'domo-php Documentation', [author], 1)]
texinfo_documents = [(master_doc, 'domo-php', u'domo-php Documentation',author, 'domo-php', 'PHP library to interact with the Domo.com API','Miscellaneous')]